// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Scope struct {
	ID   int64
	Name string
	Role string
}

type Server struct {
	ID        int64
	Name      string
	Ipv4      string
	Status    int32
	CreatedAt pgtype.Timestamp
	UpdateAt  pgtype.Timestamp
}

type User struct {
	ID       int64
	Username string
	Password string
	Email    string
	Role     string
}
